[versions]
agp = "8.2.2"
coilCompose = "2.5.0"
kotlin = "1.9.22"
compose = "1.5.1"
accompanistSwiperefresh = "0.24.13-rc"
compose-compiler = "1.5.11"
compose-material3 = "1.2.1"
androidx-activityCompose = "1.7.2"
kotlinxCoroutinesCore = "1.7.3"
lifecycleViewmodelKtx = "2.6.2"
navigationCompose = "2.7.5"
ktorClient = "2.3.5"
kotlinxDatetime = "0.4.1"
koin = "3.6.0-wasm-alpha2"
sqlDelight = "2.0.2"
material3Android = "1.3.2"
composeMultiplatform = "1.6.1"
koinCompose = "1.1.2"
kamelImage = "0.9.4"
voyagerVersion = "1.1.0-alpha04"

[libraries]
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }

kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClient" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClient" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClient" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClient" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClient" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyagerVersion" }

sql-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sql-native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sql-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

compose-material = { module = "org.jetbrains.compose.material:material", version.ref = "composeMultiplatform" }

kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamelImage" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
composeMultiplatformPlugin = { id= "org.jetbrains.compose", version.ref = "composeMultiplatform" }

